### ISSUE TITLE
missing `setuptools_scm` is causing incorrect metadata

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/dask-image-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I believe since `setuptools_scm` is missing the version of the package is appearing as `0.0.0` in the build, which is causing issues with `pip check`. See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=936824&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=1121

from https://github.com/conda-forge/ml4xcube-feedstock/pull/2

I think this is being fixed in https://github.com/conda-forge/dask-image-feedstock/pull/24, but just wanted to raise the issue just in case.

### Installed packages

```shell
dask-image:                2024.5.0-pyhd8ed1ab_0         conda-forge
```

### Environment info

```shell
conda-forge ci
```

**Comment by jakirkham** [comment]
Thanks for the report, Joshua! 🙏

This will be addressed by PR: https://github.com/conda-forge/dask-image-feedstock/pull/24

**Comment by GenevieveBuckley** [comment]
Thank you for the quick fix @jakirkham 

Sorry I didn't catch the error earlier (conda-forge doesn't make builds for pre-releases, so I didn't realise I'd need to update the setuptools dependencies there)
